import { z } from 'zod';

export const poiTypesSchema = z.object({
  accomodation: z.object({
    id: z.number(),
    children: z.object({
      tourism: z.object({
        alpine_hut: z.number(),
        apartment: z.number(),
        camp_site: z.number(),
        caravan_site: z.number(),
        chalet: z.number(),
        guest_house: z.number(),
        hostel: z.number(),
        hotel: z.number(),
        motel: z.number(),
        wilderness_hut: z.number(),
      }),
    }),
  }),
  animals: z.object({
    id: z.number(),
    children: z.object({
      amenity: z.object({
        animal_boarding: z.number(),
        animal_shelter: z.number(),
        veterinary: z.number(),
      }),
      shop: z.object({ pet: z.number() }),
    }),
  }),
  arts_and_culture: z.object({
    id: z.number(),
    children: z.object({
      amenity: z.object({
        arts_centre: z.number(),
        library: z.number(),
        place_of_worship: z.number(),
        studio: z.number(),
      }),
      tourism: z.object({ gallery: z.number(), museum: z.number() }),
    }),
  }),
  education: z.object({
    id: z.number(),
    children: z.object({
      amenity: z.object({
        college: z.number(),
        driving_school: z.number(),
        kindergarten: z.number(),
        language_school: z.number(),
        music_school: z.number(),
        school: z.number(),
        university: z.number(),
      }),
    }),
  }),
  facilities: z.object({
    id: z.number(),
    children: z.object({
      amenity: z.object({
        compressed_air: z.number(),
        bench: z.number(),
        emergency_phone: z.number(),
        clock: z.number(),
        drinking_water: z.number(),
        hunting_stand: z.number(),
        internet_cafe: z.number(),
        kneipp_water_cure: z.number(),
        post_box: z.number(),
        recycling: z.number(),
        sanitary_dump_station: z.number(),
        shelter: z.number(),
        shower: z.number(),
        table: z.number(),
        telephone: z.number(),
        toilets: z.number(),
        waste_basket: z.number(),
        waste_disposal: z.number(),
        water_point: z.number(),
      }),
      emergency: z.object({
        access_point: z.number(),
        defibrillator: z.number(),
        fire_hydrant: z.number(),
      }),
    }),
  }),
  financial: z.object({
    id: z.number(),
    children: z.object({
      amenity: z.object({
        atm: z.number(),
        bank: z.number(),
        bureau_de_change: z.number(),
      }),
    }),
  }),
  healthcare: z.object({
    id: z.number(),
    children: z.object({
      amenity: z.object({
        baby_hatch: z.number(),
        clinic: z.number(),
        dentist: z.number(),
        doctors: z.number(),
        hospital: z.number(),
        nursing_home: z.number(),
        pharmacy: z.number(),
        retirement_home: z.number(),
        social_facility: z.number(),
      }),
      healthcare: z.object({ blood_donation: z.number() }),
      'healthcare:speciality': z.object({ vaccination: z.number() }),
      vaccination: z.object({ covid19: z.number() }),
    }),
  }),
  historic: z.object({
    id: z.number(),
    children: z.object({
      historic: z.object({
        aircraft: z.number(),
        aqueduct: z.number(),
        archaeological_site: z.number(),
        castle: z.number(),
        cannon: z.number(),
        city_gate: z.number(),
        citywalls: z.number(),
        battlefield: z.number(),
        boundary_stone: z.number(),
        building: z.number(),
        farm: z.number(),
        fort: z.number(),
        gallows: z.number(),
        highwater_mark: z.number(),
        locomotive: z.number(),
        manor: z.number(),
        memorial: z.number(),
        milestone: z.number(),
        monastery: z.number(),
        monument: z.number(),
        optical_telegraph: z.number(),
        pillory: z.number(),
        ruins: z.number(),
        rune_stone: z.number(),
        ship: z.number(),
        tomb: z.number(),
        wayside_cross: z.number(),
        wayside_shrine: z.number(),
        wreck: z.number(),
      }),
    }),
  }),
  leisure_and_entertainment: z.object({
    id: z.number(),
    children: z.object({
      leisure: z.object({
        adult_gaming_centre: z.number(),
        amusement_arcade: z.number(),
        beach_resort: z.number(),
        bandstand: z.number(),
        bird_hide: z.number(),
        common: z.number(),
        dance: z.number(),
        dog_park: z.number(),
        firepit: z.number(),
        fishing: z.number(),
        fitness_centre: z.number(),
        garden: z.number(),
        golf_course: z.number(),
        hackerspace: z.number(),
        horse_riding: z.number(),
        ice_rink: z.number(),
        marina: z.number(),
        miniature_golf: z.number(),
        nature_reserve: z.number(),
        park: z.number(),
        picnic_table: z.number(),
        pitch: z.number(),
        playground: z.number(),
        sauna: z.number(),
        slipway: z.number(),
        sports_centre: z.number(),
        stadium: z.number(),
        summer_camp: z.number(),
        swimming_area: z.number(),
        swimming_pool: z.number(),
        track: z.number(),
        turkish_bath: z.number(),
        water_park: z.number(),
        wildlife_hide: z.number(),
      }),
      highway: z.object({ raceway: z.number() }),
      amenity: z.object({
        brothel: z.number(),
        casino: z.number(),
        cinema: z.number(),
        dive_centre: z.number(),
        dojo: z.number(),
        gambling: z.number(),
        nightclub: z.number(),
        planetarium: z.number(),
        public_bath: z.number(),
        social_centre: z.number(),
        spa: z.number(),
        stripclub: z.number(),
      }),
      tourism: z.object({
        aquarium: z.number(),
        theme_park: z.number(),
        zoo: z.number(),
      }),
    }),
  }),
  natural: z.object({
    id: z.number(),
    children: z.object({
      natural: z.object({
        cave_entrance: z.number(),
        beach: z.number(),
        geyser: z.number(),
        peak: z.number(),
        rock: z.number(),
        saddle: z.number(),
        spring: z.number(),
        volcano: z.number(),
        water: z.number(),
      }),
    }),
  }),
  public_places: z.object({
    id: z.number(),
    children: z.object({
      amenity: z.object({
        embassy: z.number(),
        crematorium: z.number(),
        community_centre: z.number(),
        courthouse: z.number(),
        coworking_space: z.number(),
        crypt: z.number(),
        fire_station: z.number(),
        grave_yard: z.number(),
        police: z.number(),
        post_office: z.number(),
        prison: z.number(),
        ranger_station: z.number(),
        rescue_station: z.number(),
        townhall: z.number(),
      }),
    }),
  }),
  service: z.object({
    id: z.number(),
    children: z.object({
      shop: z.object({
        beauty: z.number(),
        estate_agent: z.number(),
        dry_cleaning: z.number(),
        glaziery: z.number(),
        hairdresser: z.number(),
        laundry: z.number(),
        massage: z.number(),
        tailor: z.number(),
        tattoo: z.number(),
      }),
      amenity: z.object({ photo_booth: z.number() }),
    }),
  }),
  shops: z.object({
    id: z.number(),
    children: z.object({
      shop: z.object({
        agrarian: z.number(),
        alcohol: z.number(),
        antiques: z.number(),
        art: z.number(),
        bag: z.number(),
        bakery: z.number(),
        bed: z.number(),
        beverages: z.number(),
        bicycle: z.number(),
        books: z.number(),
        boutique: z.number(),
        brewing_supplies: z.number(),
        business_machines: z.number(),
        butcher: z.number(),
        cafe: z.number(),
        camera: z.number(),
        candles: z.number(),
        car: z.number(),
        car_parts: z.number(),
        carpet: z.number(),
        curtain: z.number(),
        cheese: z.number(),
        chemist: z.number(),
        chocolate: z.number(),
        clothes: z.number(),
        coffee: z.number(),
        computer: z.number(),
        confectionery: z.number(),
        convenience: z.number(),
        copyshop: z.number(),
        cosmetics: z.number(),
        dairy: z.number(),
        deli: z.number(),
        department_store: z.number(),
        doityourself: z.number(),
        electrical: z.number(),
        electronics: z.number(),
        erotic: z.number(),
        'e-cigarette': z.number(),
        farm: z.number(),
        fashion: z.number(),
        fishing: z.number(),
        florist: z.number(),
        funeral_directors: z.number(),
        furniture: z.number(),
        games: z.number(),
        garden_centre: z.number(),
        garden_furniture: z.number(),
        gas: z.number(),
        general: z.number(),
        gift: z.number(),
        greengrocer: z.number(),
        grocery: z.number(),
        interior_decoration: z.number(),
        hairdresser_supply: z.number(),
        hardware: z.number(),
        hearing_aids: z.number(),
        herbalist: z.number(),
        hifi: z.number(),
        houseware: z.number(),
        hunting: z.number(),
        insurance: z.number(),
        jewelry: z.number(),
        leather: z.number(),
        locksmith: z.number(),
        kiosk: z.number(),
        kitchen: z.number(),
        lamps: z.number(),
        lottery: z.number(),
        mall: z.number(),
        medical_supply: z.number(),
        mobile_phone: z.number(),
        model: z.number(),
        motorcycle: z.number(),
        music: z.number(),
        musical_instrument: z.number(),
        nutrition_supplements: z.number(),
        newsagent: z.number(),
        optician: z.number(),
        organic: z.number(),
        outdoor: z.number(),
        paint: z.number(),
        pastry: z.number(),
        perfumery: z.number(),
        photo: z.number(),
        pyrotechnics: z.number(),
        radiotechnics: z.number(),
        seafood: z.number(),
        second_hand: z.number(),
        security: z.number(),
        shoes: z.number(),
        spices: z.number(),
        sports: z.number(),
        stationery: z.number(),
        supermarket: z.number(),
        swimming_pool: z.number(),
        tea: z.number(),
        ticket: z.number(),
        tiles: z.number(),
        tobacco: z.number(),
        toys: z.number(),
        trophy: z.number(),
        tyres: z.number(),
        variety_store: z.number(),
        video: z.number(),
        video_games: z.number(),
        watches: z.number(),
        weapons: z.number(),
        wine: z.number(),
      }),
      amenity: z.object({
        marketplace: z.number(),
        vending_machine: z.number(),
      }),
    }),
  }),
  sustenance: z.object({
    id: z.number(),
    children: z.object({
      amenity: z.object({
        bar: z.number(),
        bbq: z.number(),
        biergarten: z.number(),
        cafe: z.number(),
        drinking_water: z.number(),
        fast_food: z.number(),
        food_court: z.number(),
        ice_cream: z.number(),
        pub: z.number(),
        restaurant: z.number(),
      }),
    }),
  }),
  transport: z.object({
    id: z.number(),
    children: z.object({
      aeroway: z.object({
        aerodrome: z.number(),
        helipad: z.number(),
        heliport: z.number(),
      }),
      amenity: z.object({
        bicycle_parking: z.number(),
        bicycle_rental: z.number(),
        bicycle_repair_station: z.number(),
        boat_sharing: z.number(),
        bus_station: z.number(),
        bus_stop: z.number(),
        car_rental: z.number(),
        car_repair: z.number(),
        car_sharing: z.number(),
        car_wash: z.number(),
        charging_station: z.number(),
        ev_charging: z.number(),
        ferry_terminal: z.number(),
        fuel: z.number(),
        motorcycle_parking: z.number(),
        parking: z.number(),
        parking_entrance: z.number(),
        parking_space: z.number(),
        taxi: z.number(),
      }),
      railway: z.object({
        halt: z.number(),
        station: z.number(),
        tram_stop: z.number(),
      }),
      public_transport: z.object({
        platform: z.number(),
        stop_position: z.number(),
        stop_area: z.number(),
        station: z.number(),
      }),
    }),
  }),
  tourism: z.object({
    id: z.number(),
    children: z.object({
      tourism: z.object({
        artwork: z.number(),
        attraction: z.number(),
        information: z.number(),
        picnic_site: z.number(),
        viewpoint: z.number(),
      }),
      amenity: z.object({ fountain: z.number() }),
      shop: z.object({ travel_agency: z.number() }),
    }),
  }),
});
export type PoiTypes = z.infer<typeof poiTypesSchema>;
