image: node:current-alpine
pages:
  cache:
    paths:
      - node_modules/
  script:
    - npm install -g @angular/cli@10.1.3
    - npm install
    - ng build
    - mkdir public
    - mv dist/locator/* public/
  artifacts:
    paths:
      - public
  only:
    - master
    - pages
