image: node:current-alpine
pages:
  cache:
    paths:
      - node_modules/
  script:
    - npm install -g @angular/cli
    - npm install
    - ng build
    - mkdir public
    - mv dist/locator/* public/
    - echo "/* /index.html 200" > public/_redirects
  artifacts:
    paths:
      - public
  only:
    - master
    - pages
