/**
 * Teleport
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { GeonameID } from './geonameID';

/**
 * The detailed information about an administrative division
 */
export interface Admin1Division {
  /**
   * The GeoNames.org ID of the administrative division
   */
  geoname_id: GeonameID;
  /**
   * The GeoNames.org admin1 code of the administrative division
   */
  geonames_admin1Code: string;
  /**
   * The name of the administrative division
   */
  name: string;
}
