/**
 * Teleport
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { LatLonBoundingBox } from './latLonBoundingBox';


/**
 * Coordinates of a geographic bounding box in various geocoding systems
 */
export interface BoundingBox { 
    /**
     * Bounding box identified by two latitude-longitude coordinate pairs
     */
    latlon: LatLonBoundingBox;
}
