/**
 * Teleport
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AlternateName } from './alternateName';


/**
 * Individual search result of a city search
 */
export interface CitySearchResultsItem { 
    /**
     * List of alternate names that were used for matching the city to the search criteria
     */
    matchingAlternateNames: Array<AlternateName>;
    /**
     * The full name of the city that contains all terms in the search parameter
     */
    matchingFullName: string;
}
