/**
 * Teleport
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Coordinates } from './coordinates';
import { GeonameID } from './geonameID';
import { Population } from './population';


/**
 * Detailed information about a city
 */
export interface City { 
    /**
     * The full name of the city, qualified with country and administrative division (if present)
     */
    fullName: string;
    /**
     * The GeoNames.org ID of the city
     */
    geonameId: GeonameID;
    /**
     * The coordinates of the city center
     */
    location: Coordinates;
    /**
     * The name of the city
     */
    name: string;
    /**
     * The population estimate of the city
     */
    population?: Population;
}
