/**
 * Teleport
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { City } from './city';
import { CitySearchResultsItem } from './citySearchResultsItem';
import { UrbanArea } from './urbanArea';

/**
 * The results of a city search
 */
export interface baseResult {
  /**
   * Number of cities found
   */
  count: number;
}
export type CitySearchResults = baseResult & {
  _embedded: {
    'city:search-results': [
      CitySearchResultsItem & {
        _embedded: {
          'city:item': City & {
            _embedded: {
              'city:urban_area': UrbanArea;
            };
          };
        };
        _links: {
          'city:item': {
            href: string;
          };
        };
      }
    ];
  };
};
