/**
 * Teleport
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * The detailed information for a continent
 */
export interface Continent {
  /**
   * The GeoNames code for the continent
   */
  geonames_code: string;
  /**
   * The name of the continent
   */
  name: string;
}
