/**
 * Teleport
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { GeoHash } from './geoHash';
import { LatLon } from './latLon';


/**
 * Coordinates of a geographic point in various geocoding systems
 */
export interface Coordinates { 
    /**
     * Coordinates identified by GeoHash
     */
    geohash: GeoHash;
    /**
     * Coordinates identified by the latitude-longitude coordinate pair
     */
    latlon: LatLon;
}
