/**
 * Teleport
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * Salary 25th, 50th and 75th percentiles for a job and country combination
 */
export interface CountryJobSalaryPercentiles { 
    /**
     * Salary in the 25th percentile in US dollars
     */
    percentile25: number;
    /**
     * Mean salary (50th percentile) in US dollars
     */
    percentile50: number;
    /**
     * Salary in the 75th percentile in US dollars
     */
    percentile75: number;
}
