/**
 * Teleport
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CurrencyCode } from './currencyCode';
import { GeonameID } from './geonameID';
import { ISOAlpha2Code } from './iSOAlpha2Code';
import { ISOAlpha3Code } from './iSOAlpha3Code';
import { Population } from './population';


/**
 * The detailed information for a country
 */
export interface Country { 
    /**
     * The code of the main currency used by the country
     */
    currencyCode?: CurrencyCode;
    /**
     * The GeoNames.org ID of the country
     */
    geonameId?: GeonameID;
    /**
     * The ISO-3166-1 alpha-2 code for the country
     */
    isoAlpha2: ISOAlpha2Code;
    /**
     * The ISO-3166-1 alpha-3 code for the country
     */
    isoAlpha3: ISOAlpha3Code;
    /**
     * The name of the country
     */
    name: string;
    /**
     * The population estimate for the country
     */
    population: Population;
}
