/**
 * Teleport
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CountryJobSalary } from './countryJobSalary';


/**
 * Teleport City salaries for a country
 */
export interface CountrySalaries { 
    /**
     * All salaries for a country
     */
    salaries: Array<CountryJobSalary>;
}
