/**
 * Teleport
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CountryJob } from './countryJob';
import { CountryJobSalaryPercentiles } from './countryJobSalaryPercentiles';


/**
 * Salary information for a particular job in a country
 */
export interface CountryJobSalary { 
    /**
     * Job information
     */
    job: CountryJob;
    /**
     * Salary 25th, 50th and 75th percentiles for a job and country combination
     */
    salaryPercentiles: CountryJobSalaryPercentiles;
}
