/**
 * Teleport
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Detailed information for a traveling people group
 */
export interface FlockMeetingPlacePeopleGroup {
  /**
   * Flight ticket cost in USD for this route
   */
  cost_usd: number;
  /**
   * Departure date of an example trip (Monday) in YYYY-MM-DD format
   */
  departure_date: string;
  /**
   * Destination airport IATA code (null if this people group is not flying)
   */
  destination_airport: string;
  /**
   * Traveling distance for this people group
   */
  distance_km: number;
  /**
   * Flight time in hours for this people group
   */
  flight_time_h: number;
  /**
   * Number of hops (flights) in this route
   */
  number_of_hops: number;
  /**
   * Number of people in this people group
   */
  number_of_people: number;
  /**
   * Return date of an example trip (Sunday) in YYYY-MM-DD format
   */
  return_date: string;
  /**
   * Source airport IATA code (null if this people group is not flying)
   */
  source_airport: string;
  /**
   * Traveling time (flight time + ground transport) in hours for this people group
   */
  time_h: number;
}
