/**
 * Teleport
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { FlockPlanRequestPeopleGroup } from './flockPlanRequestPeopleGroup';

/**
 * Request for creating a Flock plan for gathering people around the world to a common meeting place
 */
export interface FlockPlanRequest {
  /**
   * The list of people groups to be included in the plan
   */
  people_groups: Array<FlockPlanRequestPeopleGroup>;
}
