/**
 * Teleport
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * Detailed information for a traveling people group
 */
export interface FlockMeetingPlacePeopleGroup { 
    /**
     * Flight ticket cost in USD for this route
     */
    costUsd: number;
    /**
     * Departure date of an example trip (Monday) in YYYY-MM-DD format
     */
    departureDate: string;
    /**
     * Destination airport IATA code (null if this people group is not flying)
     */
    destinationAirport: string;
    /**
     * Traveling distance for this people group
     */
    distanceKm: number;
    /**
     * Flight time in hours for this people group
     */
    flightTimeH: number;
    /**
     * Number of hops (flights) in this route
     */
    numberOfHops: number;
    /**
     * Number of people in this people group
     */
    numberOfPeople: number;
    /**
     * Return date of an example trip (Sunday) in YYYY-MM-DD format
     */
    returnDate: string;
    /**
     * Source airport IATA code (null if this people group is not flying)
     */
    sourceAirport: string;
    /**
     * Traveling time (flight time + ground transport) in hours for this people group
     */
    timeH: number;
}
