/**
 * Teleport
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { GeonameID } from './geonameID';
import { Latitude } from './latitude';
import { Longitude } from './longitude';


/**
 * Detailed information for the meeting place city
 */
export interface FlockMeetingPlaceCity { 
    /**
     * Name of the country where the city is located
     */
    country: string;
    geonameId: GeonameID;
    latitude: Latitude;
    longitude: Longitude;
    /**
     * Name of the country where the city is located
     */
    name: string;
    /**
     * Code of the state where the city is located
     */
    stateCode: string;
    /**
     * Long name of the city
     */
    title: string;
}
