/**
 * Teleport
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * Text with limited HTML formatting (e.g. bold tags) - should not be HTML-encoded. Guaranteed to be safe not to include unsafe tags.
 */
export type HTMLFormattedText = string;
