/**
 * Teleport
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Latitude } from './latitude';
import { Longitude } from './longitude';


/**
 * A location on Earth identified by the latitude-longitude coordinate pair
 */
export interface LatLon { 
    latitude: Latitude;
    longitude: Longitude;
}
