/**
 * Teleport
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { URL } from './uRL';


/**
 * The author, source and license for a photo
 */
export interface PhotoAttribution { 
    /**
     * The name of the license
     */
    license?: string;
    /**
     * The full name of the photographer
     */
    photographer?: string;
    /**
     * The name of the site where this photo was included from
     */
    site?: string;
    /**
     * The URL of the original photo
     */
    source?: URL;
}
