/**
 * Teleport
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { IANATimezoneName } from './iANATimezoneName';


/**
 * Detailed information of a timezone
 */
export interface Timezone { 
    /**
     * IANA/Olson/tzdata database name for the timezone
     */
    ianaName: IANATimezoneName;
}
