/**
 * Teleport
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { TZOffsetMinutes } from './tZOffsetMinutes';
import { TZTransitionTime } from './tZTransitionTime';


/**
 * The time offsets of a timezone as of a specified time
 */
export interface TimezoneOffsets { 
    /**
     * The base offset in minutes
     */
    baseOffsetMin: TZOffsetMinutes;
    /**
     * The daylight savings time (DST) offset in minutes
     */
    dstOffsetMin: TZOffsetMinutes;
    /**
     * The time these offsets are in effect until
     */
    endTime?: TZTransitionTime;
    /**
     * The 3 or 4-letter short name of the timezone
     */
    shortName: string;
    /**
     * The total offset of the timezone in minutes (equal to base_offset_min + dst_offset_min)
     */
    totalOffsetMin: TZOffsetMinutes;
    /**
     * The time these offsets are in effect from
     */
    transitionTime: TZTransitionTime;
}
