/**
 * Teleport
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { UrbanAreaJob } from './urbanAreaJob';
import { UrbanAreaJobSalaryPercentiles } from './urbanAreaJobSalaryPercentiles';

/**
 * Salary information for a particular job in an urban area
 */
export interface UrbanAreaJobSalary {
  /**
   * Job information
   */
  job: UrbanAreaJob;
  /**
   * Salary 25th, 50th and 75th percentiles for a job and urban area combination
   */
  salary_percentiles: UrbanAreaJobSalaryPercentiles;
}
