/**
 * Teleport
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CssColor } from './cssColor';


/**
 * The detailed category scores for an urban area
 */
export interface UrbanAreaScoreCategory { 
    /**
     * The HTML/CSS color used to display the score bar in Teleport City Profiles
     */
    color: CssColor;
    /**
     * The name of the score category
     */
    name: string;
    /**
     * The score for the category (out of 10)
     */
    scoreOutOf10: number;
}
