/**
 * Teleport
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * Job ID and name
 */
export interface UrbanAreaJob { 
    /**
     * Job unique identifier
     */
    id: string;
    /**
     * Job title
     */
    name?: string;
}
