/**
 * Teleport
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { UrbanAreaDetailDataPoint } from './urbanAreaDetailDataPoint';


/**
 * Category detailed data for an urban area
 */
export interface UrbanAreaDetailCategory { 
    /**
     * Detailed data available for category
     */
    data: Array<UrbanAreaDetailDataPoint>;
    /**
     * Fixed identifier for category
     */
    id: string;
    /**
     * Label describing category
     */
    label: string;
}
