/**
 * Teleport
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { HTMLFormattedText } from './hTMLFormattedText';
import { UrbanAreaScoreCategory } from './urbanAreaScoreCategory';


/**
 * The Teleport City Scores for an urban area
 */
export interface UrbanAreaScores { 
    /**
     * The detailed category scores for the urban area
     */
    categories: Array<UrbanAreaScoreCategory>;
    /**
     * Textual summary of the city's pros and cons
     */
    summary?: HTMLFormattedText;
    /**
     * The aggregate Teleport City Score (out of 100)
     */
    teleportCityScore: number;
}
