/**
 * Teleport
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { BoundingBox } from './boundingBox';
import { URL } from './uRL';
import { UrbanAreaID } from './urbanAreaID';

/**
 * Teleport urban area (aka Teleport City)
 */
export interface UrbanArea {
  /**
   * Bounding box of the urban area
   */
  bounding_box: BoundingBox;
  /**
   * The continent where the urban area is located
   */
  continent?: string;
  /**
   * Full name of the urban area
   */
  full_name: string;
  /**
   * Whether the urban_area represents a government partner to Teleport
   */
  is_government_partner: boolean;
  /**
   * Name of the urban area
   */
  name: string;
  /**
   * Teleport Urban Area slug
   */
  slug: string;
  /**
   * Link to Teleport City Profile
   */
  teleport_city_url: URL;
  /**
   * Teleport Urban Area ID
   */
  ua_id: UrbanAreaID;
}
