/**
 * Teleport
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { URL } from './uRL';

/**
 * Teleport City detailed data points for an urban area
 */
export interface UrbanAreaDetailDataPoint {
  /**
   * Currency value in US dollars for a data point.
   */
  currency_dollar_value?: number;
  /**
   * Float value for a data point.
   */
  float_value?: number;
  /**
   * Fixed identifier for data point
   */
  id: string;
  /**
   * Integer value for a data point.
   */
  int_value?: number;
  /**
   * Label describing data point
   */
  label: string;
  /**
   * Percent value between 0.0 and 1.0 for a data point.
   */
  percent_value?: number;
  /**
   * String value for a data point.
   */
  string_value?: string;
  /**
   * Data type for value. The actual value is stored in field named as type + '_value'.
   */
  type: string;
  /**
   * URL provided as reference for a data point.
   */
  url_value?: URL;
}
