/**
 * Teleport
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Photo } from './photo';


/**
 * Images (photos, icons, etc) for an urban area
 */
export interface UrbanAreaImages { 
    /**
     * List of photos
     */
    photos?: Array<Photo>;
}
