export * from './cities.service';
import { CitiesService } from './cities.service';
export * from './continents.service';
import { ContinentsService } from './continents.service';
export * from './countries.service';
import { CountriesService } from './countries.service';
export * from './flock.service';
import { FlockService } from './flock.service';
export * from './ipaddress.service';
import { IpaddressService } from './ipaddress.service';
export * from './locations.service';
import { LocationsService } from './locations.service';
export * from './root.service';
import { RootService } from './root.service';
export * from './timezones.service';
import { TimezonesService } from './timezones.service';
export * from './urbanAreas.service';
import { UrbanAreasService } from './urbanAreas.service';
export const APIS = [CitiesService, ContinentsService, CountriesService, FlockService, IpaddressService, LocationsService, RootService, TimezonesService, UrbanAreasService];
