/**
 * Teleport
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional } from '@angular/core';
import {
  HttpClient,
  HttpHeaders,
  HttpParams,
  HttpResponse,
  HttpEvent,
} from '@angular/common/http';
import { CustomHttpUrlEncodingCodec } from '../encoder';

import { Observable } from 'rxjs';

import { Timezone } from '../model/timezone';
import { TimezoneList } from '../model/timezoneList';

import { BASE_PATH, COLLECTION_FORMATS } from '../variables';
import { Configuration } from '../configuration';

@Injectable()
export class TimezonesService {
  protected basePath = 'https://api.teleport.org/api';
  public defaultHeaders = new HttpHeaders();
  public configuration = new Configuration();

  constructor(
    protected httpClient: HttpClient,
    @Optional() @Inject(BASE_PATH) basePath: string,
    @Optional() configuration: Configuration
  ) {
    if (basePath) {
      this.basePath = basePath;
    }
    if (configuration) {
      this.configuration = configuration;
      this.basePath = basePath || configuration.basePath || this.basePath;
    }
  }

  /**
   * @param consumes string[] mime-types
   * @return true: consumes contains 'multipart/form-data', false: otherwise
   */
  private canConsumeForm(consumes: string[]): boolean {
    const form = 'multipart/form-data';
    for (const consume of consumes) {
      if (form === consume) {
        return true;
      }
    }
    return false;
  }

  /**
   * Get timezone information
   *
   * @param tzId The timezone ID, consisting of ID scheme and ID, separated by colon (e.g. iana:America/Los_Angeles). Note: if concatenating the tz_id to API URLs, the slash in timezone ID must be URL encoded (%2F).
   * @param embed Relationship paths to embed in the response
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public getTimezoneByID(
    tzId: string,
    embed?: Array<string>,
    observe?: 'body',
    reportProgress?: boolean
  ): Observable<Timezone>;
  public getTimezoneByID(
    tzId: string,
    embed?: Array<string>,
    observe?: 'response',
    reportProgress?: boolean
  ): Observable<HttpResponse<Timezone>>;
  public getTimezoneByID(
    tzId: string,
    embed?: Array<string>,
    observe?: 'events',
    reportProgress?: boolean
  ): Observable<HttpEvent<Timezone>>;
  public getTimezoneByID(
    tzId: string,
    embed?: Array<string>,
    observe: any = 'body',
    reportProgress: boolean = false
  ): Observable<any> {
    if (tzId === null || tzId === undefined) {
      throw new Error(
        'Required parameter tzId was null or undefined when calling getTimezoneByID.'
      );
    }

    let queryParameters = new HttpParams({
      encoder: new CustomHttpUrlEncodingCodec(),
    });
    if (embed) {
      embed.forEach((element) => {
        queryParameters = queryParameters.append('embed', <any>element);
      });
    }

    let headers = this.defaultHeaders;

    // to determine the Accept header
    let httpHeaderAccepts: string[] = ['application/vnd.teleport.v1+json'];
    const httpHeaderAcceptSelected: string | undefined =
      this.configuration.selectHeaderAccept(httpHeaderAccepts);
    if (httpHeaderAcceptSelected != undefined) {
      headers = headers.set('Accept', httpHeaderAcceptSelected);
    }

    // to determine the Content-Type header
    const consumes: string[] = ['application/vnd.teleport.v1+json'];

    return this.httpClient.get<Timezone>(
      `${this.basePath}/timezones/${encodeURIComponent(String(tzId))}/`,
      {
        params: queryParameters,
        withCredentials: this.configuration.withCredentials,
        headers: headers,
        observe: observe,
        reportProgress: reportProgress,
      }
    );
  }

  /**
   * Get timezone information
   *
   * @param tzId The timezone ID, consisting of ID scheme and ID, separated by colon (e.g. iana:America/Los_Angeles). Note: if concatenating the tz_id to API URLs, the slash in timezone ID must be URL encoded (%2F).
   * @param date Date/time as of what time the timezone offsets should be provided
   * @param embed Relationship paths to embed in the response
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public getTimezoneByID_1(
    tzId: string,
    date: string,
    embed?: Array<string>,
    observe?: 'body',
    reportProgress?: boolean
  ): Observable<Timezone>;
  public getTimezoneByID_1(
    tzId: string,
    date: string,
    embed?: Array<string>,
    observe?: 'response',
    reportProgress?: boolean
  ): Observable<HttpResponse<Timezone>>;
  public getTimezoneByID_1(
    tzId: string,
    date: string,
    embed?: Array<string>,
    observe?: 'events',
    reportProgress?: boolean
  ): Observable<HttpEvent<Timezone>>;
  public getTimezoneByID_1(
    tzId: string,
    date: string,
    embed?: Array<string>,
    observe: any = 'body',
    reportProgress: boolean = false
  ): Observable<any> {
    if (tzId === null || tzId === undefined) {
      throw new Error(
        'Required parameter tzId was null or undefined when calling getTimezoneByID_1.'
      );
    }

    if (date === null || date === undefined) {
      throw new Error(
        'Required parameter date was null or undefined when calling getTimezoneByID_1.'
      );
    }

    let queryParameters = new HttpParams({
      encoder: new CustomHttpUrlEncodingCodec(),
    });
    if (date !== undefined && date !== null) {
      queryParameters = queryParameters.set('date', <any>date);
    }
    if (embed) {
      embed.forEach((element) => {
        queryParameters = queryParameters.append('embed', <any>element);
      });
    }

    let headers = this.defaultHeaders;

    // to determine the Accept header
    let httpHeaderAccepts: string[] = ['application/vnd.teleport.v1+json'];
    const httpHeaderAcceptSelected: string | undefined =
      this.configuration.selectHeaderAccept(httpHeaderAccepts);
    if (httpHeaderAcceptSelected != undefined) {
      headers = headers.set('Accept', httpHeaderAcceptSelected);
    }

    // to determine the Content-Type header
    const consumes: string[] = ['application/vnd.teleport.v1+json'];

    return this.httpClient.get<Timezone>(
      `${this.basePath}/timezones/${encodeURIComponent(String(tzId))}/offsets/`,
      {
        params: queryParameters,
        withCredentials: this.configuration.withCredentials,
        headers: headers,
        observe: observe,
        reportProgress: reportProgress,
      }
    );
  }

  /**
   * List all timezones
   *
   * @param embed Relationship paths to embed in the response
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public listTimezones(
    embed?: Array<string>,
    observe?: 'body',
    reportProgress?: boolean
  ): Observable<TimezoneList>;
  public listTimezones(
    embed?: Array<string>,
    observe?: 'response',
    reportProgress?: boolean
  ): Observable<HttpResponse<TimezoneList>>;
  public listTimezones(
    embed?: Array<string>,
    observe?: 'events',
    reportProgress?: boolean
  ): Observable<HttpEvent<TimezoneList>>;
  public listTimezones(
    embed?: Array<string>,
    observe: any = 'body',
    reportProgress: boolean = false
  ): Observable<any> {
    let queryParameters = new HttpParams({
      encoder: new CustomHttpUrlEncodingCodec(),
    });
    if (embed) {
      embed.forEach((element) => {
        queryParameters = queryParameters.append('embed', <any>element);
      });
    }

    let headers = this.defaultHeaders;

    // to determine the Accept header
    let httpHeaderAccepts: string[] = ['application/vnd.teleport.v1+json'];
    const httpHeaderAcceptSelected: string | undefined =
      this.configuration.selectHeaderAccept(httpHeaderAccepts);
    if (httpHeaderAcceptSelected != undefined) {
      headers = headers.set('Accept', httpHeaderAcceptSelected);
    }

    // to determine the Content-Type header
    const consumes: string[] = ['application/vnd.teleport.v1+json'];

    return this.httpClient.get<TimezoneList>(`${this.basePath}/timezones/`, {
      params: queryParameters,
      withCredentials: this.configuration.withCredentials,
      headers: headers,
      observe: observe,
      reportProgress: reportProgress,
    });
  }
}
